name: Build Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Flutter 3.22.2 with Dart 3.5.0
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.22.2 --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Enable Web
        run: flutter config --enable-web

      - name: Run flutter doctor (just for log)
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: build/web
