name: Build Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - name: Enable Web (optional)
        run: flutter config --enable-web

      - name: Run Flutter Doctor (for log)
        run: flutter doctor -v

      - name: Install Dependencies
        run: flutter pub get

      # Uncomment if using generated code (e.g., json_serializable)
      # - name: Run Code Generation
      #   run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Upload Build Output
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web
          path: build/web
